# Site settings
title: Game Developer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Programmer, designer, artist.
url: "http://yourdomain.com" # the base hostname & protocol for your site
# If you want to include twitter, remove # on next line and set username
# twitter_username: jekyllrb
github_username:  gamingportfolio

# Build settings
markdown: kramdown
permalink: pretty
